name: AI Log Analyzer CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 999

      - name: Install dependencies
        run: npm install

      - name: Run application
        run: node hello.js